### ISSUE TITLE
parameter name with full stops in them

### ISSUE THREAD

**Issue by pollen8** [rtk-incubator/rtk-query-codegen#35]
Hi
I'm investigating using rtk-query-codegen at our work. We currently have a large OpenAPI v2 file generated from a proto definition.
Some of its query parameter names are using a dot notation Eg `filter.name`. 

To replicate more easily I modified the pets swagger file so that `"/pet/findByStatus"` has a parameter `"name": "status.foo",` 

and when I run 
```npm run prepare && npm run test:update```

I see this error being generated:
```
SyntaxError: ',' expected. (10:77)

   9 |         findPetsByStatus: build.query<FindPetsByStatusApiResponse, FindPetsByStatusApiArg>({
> 10 |             query: queryArg => ({ url: `/pet/findByStatus`, params: { status.foo: queryArg.statusFoo } })
     |                                                                             ^
  11 |         })

```
I have tinkered with the code in generate.ts to avoid the error, but then this will quote all parameters regardless of whether they require it or not. 
To be fair I've not even got to the point of integrating the api as I've got some other issues I need to investigate before the generator works.
I guess my question is: is this an acceptable solution to start work on a pull request or am I totally off base with how things should work. 

```
function generateQuerArgObjectLiteralExpression(queryArgs: QueryArgDefinition[], rootObject: ts.Identifier) {
  return factory.createObjectLiteralExpression(
    queryArgs.map(
      (param) => {
        const origName = factory.createIdentifier(param.originalName);
        const name: ts.Identifier = {
          ...origName,
          escapedText: `'${origName.escapedText}'` as any,
        };

        return factory.createPropertyAssignment(
          name,
          factory.createPropertyAccessExpression(rootObject, factory.createIdentifier(param.name))
        )
      }
    )
  );
}
```

**Comment by pollen8** [comment]
Perhaps this is the same issue as https://github.com/rtk-incubator/rtk-query-codegen/issues/15
in which case would fixing this simply be a question of updating oazapfts in the package.json ?

**Comment by phryneas** [comment]
Would be perfect to wait for them to do a release since the PRs finally got merged. You could nudge them a bit ;)

**Comment by pollen8** [comment]
hi - I might be wrong but it looks like version 3.3.1 has the required fix https://github.com/cellular/oazapfts/commit/81513f814302c76a8254865eaf2e0b0aa0bb9b2d ?

**Comment by pollen8** [comment]
ignore that, I updated locally and the problem is still there

**Comment by tevariou** [comment]
same issue with parameters with '-' in them. For example:

```
/StructureDefinition:
    get:
      tags:
        - StructureDefinition
      summary: "search-type: Update an existing StructureDefinition instance, or create\
        \ using a client-assigned ID"
      description: This is a search type
      parameters:
        - name: context-type-value
          in: query
          description: A use context type and value assigned to the structure definition
          style: simple
```
